### ISSUE TITLE
Support for GHE?

### ISSUE THREAD

**Issue by heylookltsme** [ookami-kb/gh-pr-size-watcher#10]
Hello! I'd love to use this action in a Github Enterprise environment, but I keep getting a bad credentials error. I suspect the action is making requests against github.com. Is there a way to configure it for GHE? Thanks!

**Comment by heylookltsme** [comment]
I dug into it a little and it looks like the github action should use [urls set in the environment](https://github.com/actions/toolkit/blob/1589a5c066fbe34ed1c828e9b81b9f206f9a3a40/packages/github/src/context.ts#L49-L50), but I tried that and no luck. 👎🏻  

Maybe updating the `@actions/github` dependency is all that's needed. It looks like it's a few versions behind.

**Comment by ookami-kb** [comment]
Hey, I've updated all the dependencies in `v1.4.0`. Can you please check it as I don't have access to GHE?

**Comment by heylookltsme** [comment]
Works perfectly, thanks much! 🚀
