### ISSUE TITLE
"Node.js 12 actions are deprecated" warning using this action

### ISSUE THREAD

**Issue by matteovivona** [ookami-kb/gh-pr-size-watcher#9]
I think you need to update the action to Node.js 16. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by ookami-kb** [comment]
The action already uses node16 for quite a long time, are you sure this warning is coming from this action?

**Comment by matteovivona** [comment]
GitHub summary points me to this Action

![Screenshot 2023-01-30 at 17 57 24](https://user-images.githubusercontent.com/6388707/215543592-4d3c27f9-0344-409f-bae7-4f53b68e87c5.png)

**Comment by ookami-kb** [comment]
Can you try the latest `v1.4.0` please?

**Comment by matteovivona** [comment]
ok ..looks like @v1 points to an older version
